services:
  db:
    image: postgres:15
    container_name: nutriwizard-db
    restart: always
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: NutriWizard

  backend:
    build: ./backend
    container_name: nutriwizard-backend
    restart: always
    ports:
      - "5001:5001"
    environment:
      DB_NAME: NutriWizard
      DB_USER: test
      DB_PASSWORD: test
      DB_HOST: db
      DB_DIALECT: postgres
      JWT_SECRET: hhoCtwg2v6eZsPS8hybCqKsCYRH8fYYnR73S5+jQvO1tp6vF6s4+l8QIdqUCm3vCrhIOEP5hdc+jQQ7YEkr84w==
      PORT: 5001
    volumes:
      - ./backend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: nutriwizard-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: true
      HOST: 0.0.0.0
      PORT: 3000
      NEXT_PUBLIC_API_URL: http://localhost:5001
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    command: npm start
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  postgres_data: